services:
  application:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www
    ports:
      - "8080:8080"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: teste
      DB_USERNAME: root
      DB_PASSWORD: root
    depends_on:
      - mysql
    
  mysql:
    image: bitnami/mysql:latest
    ports:
      - '3307:3306'
    environment:
      - MYSQL_DATABASE=teste
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - teste_data:/bitnami/mysql

volumes:
  teste_data: